### ISSUE TITLE
not an issue but just something to keep your workflow organized

### ISSUE THREAD

**Issue by Mootbing** [ksu-tech/ksubot-and-ksubotdev#12]
make a GitHub project and use it to organize your thoughts and ideas
if you're not sure how to do that, visit [my repo](https://github.com/weakunix/python_git/projects)

**Comment by ksu-tech** [comment]
ok cow

**Comment by ksu-tech** [comment]
moo

**Comment by Mootbing** [comment]
smhmh imagine being messie (says me which haven't cleaned room in like years)

**Comment by ksu-tech** [comment]
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

**Comment by ksu-tech** [comment]
illegal advert
