### ISSUE TITLE
I like your vc.js G

### ISSUE THREAD

**Issue by Mootbing** [ksu-tech/ksubot-and-ksubotdev#13]
don't make the mistake I did when I made my bot. Use different files and folders to stay organized so it doesn't blimp up into like a 2k line code that is hard to maintain AF. move the kick function and ban function to a seperate kick.js and ban.js, overall you should have one main.js and the rest of them should be in folders. Just a suggestion. Not needed.

**Comment by ksu-tech** [comment]
ok cow

**Comment by Mootbing** [comment]
yes ok in deed

**Comment by ksu-tech** [comment]
moooooooooooooooo

**Comment by Mootbing** [comment]
moooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
